"""May--Nowakowski Section 5 full-secret modular-hint construction.

Equation (20) is implemented exactly. The optional sublattice/reduction path
adapts Algorithm 1 to the modular-hint block and requires ``fpylll``. Its
scaling choice remains a documented heuristic and therefore cannot silently
serve as a headline B2 result without the recorded invariant checks.
"""

from __future__ import annotations

import math
import time
from dataclasses import dataclass
from typing import Any, Sequence

import numpy as np

from ..modular import centered_lift, centered_vector
from .base import CandidateList


class BackendUnavailable(RuntimeError):
    """Raised when the optional faithful-small lattice dependency is absent."""


class SublatticeConstructionFailed(RuntimeError):
    """Raised when Algorithm 1's zero-block check fails."""


class CertifiedTopKUnavailable(RuntimeError):
    """Raised when a constrained candidate ball cannot certify the requested K."""

    def __init__(self, message: str, metadata: dict[str, Any]):
        super().__init__(message)
        self.metadata = metadata


def bounded_schnorr_euchner(
    basis: Sequence[Sequence[int]],
    *,
    radius_squared: float,
    max_solutions: int,
    node_limit: int,
) -> tuple[list[tuple[int, ...]], dict[str, Any]]:
    """Enumerate short lattice vectors with an in-loop hard node limit.

    The lattice is generated by the rows of ``basis``. GSO data comes from
    fpylll, while traversal and its node counter are implemented here so the
    configured node limit is enforced before visiting another node. Returned
    vectors are checked again with exact integer norms.
    """

    try:
        from fpylll import GSO, IntegerMatrix
    except ImportError as exc:
        raise BackendUnavailable("fpylll is required for bounded GSO enumeration") from exc
    if radius_squared <= 0 or max_solutions <= 0 or node_limit <= 0:
        raise ValueError("radius, solution budget, and node limit must be positive")
    rows = [[int(value) for value in row] for row in basis]
    integer_basis = IntegerMatrix.from_matrix(rows)
    gso = GSO.Mat(integer_basis)
    if not gso.update_gso():
        raise RuntimeError("GSO update failed")
    dimension = integer_basis.nrows
    norms = [float(gso.get_r(i, i)) for i in range(dimension)]
    if any(not math.isfinite(value) or value <= 0 for value in norms):
        raise RuntimeError("invalid GSO diagonal")
    mu = [[0.0] * dimension for _ in range(dimension)]
    for i in range(dimension):
        for j in range(i):
            mu[i][j] = float(gso.get_mu(i, j))
    coefficients = [0] * dimension
    solutions: list[tuple[int, ...]] = []
    exact_norms: list[int] = []
    nodes = 0
    node_limit_reached = False
    solution_budget_reached = False

    def ordered_integers(center: float, maximum_deviation: float):
        nearest = int(round(center))
        maximum_offset = int(math.floor(maximum_deviation)) + 2
        yielded: set[int] = set()
        for offset in range(maximum_offset + 1):
            candidates = (nearest,) if offset == 0 else (nearest + offset, nearest - offset)
            for value in candidates:
                if value in yielded:
                    continue
                yielded.add(value)
                if abs(value - center) <= maximum_deviation + 1e-12:
                    yield value

    def recurse(level: int, partial_norm: float) -> None:
        nonlocal nodes, node_limit_reached, solution_budget_reached
        if node_limit_reached or solution_budget_reached:
            return
        if level < 0:
            if all(value == 0 for value in coefficients):
                return
            vector = tuple(
                sum(coefficients[i] * rows[i][j] for i in range(dimension))
                for j in range(len(rows[0]))
            )
            norm2 = sum(value * value for value in vector)
            if norm2 <= radius_squared * (1.0 + 1e-12):
                solutions.append(vector)
                exact_norms.append(norm2)
                if len(solutions) >= max_solutions:
                    solution_budget_reached = True
            return
        remaining = radius_squared - partial_norm
        if remaining < 0:
            return
        center = -sum(coefficients[j] * mu[j][level] for j in range(level + 1, dimension))
        deviation = math.sqrt(max(0.0, remaining / norms[level]))
        for value in ordered_integers(center, deviation):
            if nodes >= node_limit:
                node_limit_reached = True
                return
            nodes += 1
            coefficients[level] = value
            component = value - center
            recurse(level - 1, partial_norm + component * component * norms[level])
            if node_limit_reached or solution_budget_reached:
                return
        coefficients[level] = 0

    recurse(dimension - 1, 0.0)
    order = sorted(range(len(solutions)), key=lambda index: exact_norms[index])
    return [solutions[index] for index in order], {
        "enumeration_nodes": nodes,
        "enumeration_node_limit": node_limit,
        "enumeration_node_limit_reached": node_limit_reached,
        "enumeration_solution_budget_reached": solution_budget_reached,
        "enumeration_complete_within_bounds": not node_limit_reached and not solution_budget_reached,
        "enumerated_exact_norms": [exact_norms[index] for index in order],
        "enumeration_label": "PROJECT_DERIVATION / bounded Schnorr-Euchner traversal",
    }


def bounded_cvp_schnorr_euchner(
    basis: Sequence[Sequence[int]],
    *,
    offset: Sequence[int],
    radius_squared: float,
    max_slice_vectors: int,
    node_limit: int,
    fixed_embedding_coordinate: int = -1,
) -> tuple[list[tuple[int, ...]], dict[str, Any]]:
    """Completely enumerate one affine embedding slice within a norm ball.

    ``basis`` generates the homogeneous ``t=0`` slice and ``offset`` is one
    public point in the requested affine slice.  The traversal enumerates
    lattice points ``offset + z*basis`` and appends one fixed embedding
    coordinate.  A raw-vector cap remains only as a resource guard: hitting it
    marks the ball incomplete and therefore unusable for certified top-K.
    """

    try:
        from fpylll import GSO, IntegerMatrix
    except ImportError as exc:
        raise BackendUnavailable("fpylll is required for bounded CVP enumeration") from exc
    if radius_squared < fixed_embedding_coordinate * fixed_embedding_coordinate:
        return [], {
            "enumeration_nodes": 0,
            "enumeration_node_limit": int(node_limit),
            "enumeration_node_limit_reached": False,
            "enumeration_slice_vector_limit": int(max_slice_vectors),
            "enumeration_slice_vector_limit_reached": False,
            "enumeration_complete_within_bounds": True,
            "raw_slice_vector_count": 0,
            "enumerated_exact_norms": [],
            "enumeration_label": "PROJECT_DERIVATION / constrained affine-slice CVP traversal",
        }
    if max_slice_vectors <= 0 or node_limit <= 0:
        raise ValueError("slice-vector and node limits must be positive")
    rows = [[int(value) for value in row] for row in basis]
    affine_offset = [int(value) for value in offset]
    if not rows or any(len(row) != len(affine_offset) for row in rows):
        raise ValueError("constrained basis and offset dimensions differ")
    if len(rows) != len(affine_offset):
        raise ValueError("constrained slice basis must be square and full rank")
    integer_basis = IntegerMatrix.from_matrix(rows)
    gso = GSO.Mat(integer_basis)
    if not gso.update_gso():
        raise RuntimeError("GSO update failed for constrained slice")
    dimension = len(rows)
    norms = [float(gso.get_r(i, i)) for i in range(dimension)]
    if any(not math.isfinite(value) or value <= 0 for value in norms):
        raise RuntimeError("invalid constrained-slice GSO diagonal")
    mu = [[0.0] * dimension for _ in range(dimension)]
    gram_schmidt_rows: list[list[float]] = []
    for i in range(dimension):
        for j in range(i):
            mu[i][j] = float(gso.get_mu(i, j))
        vector = [float(value) for value in rows[i]]
        for j in range(i):
            coefficient = mu[i][j]
            for coordinate in range(dimension):
                vector[coordinate] -= coefficient * gram_schmidt_rows[j][coordinate]
        gram_schmidt_rows.append(vector)
    target = [-value for value in affine_offset]
    target_coordinates = [
        sum(target[j] * gram_schmidt_rows[i][j] for j in range(dimension)) / norms[i]
        for i in range(dimension)
    ]
    coefficients = [0] * dimension
    solutions: list[tuple[int, ...]] = []
    exact_norms: list[int] = []
    nodes = 0
    node_limit_reached = False
    slice_vector_limit_reached = False
    variable_radius_squared = (
        float(radius_squared) - fixed_embedding_coordinate * fixed_embedding_coordinate
    )
    search_slack = 1e-9 * max(1.0, float(radius_squared))
    exact_acceptance_radius_squared = float(radius_squared) * (1.0 + 1e-12)

    def ordered_integers(center: float, maximum_deviation: float):
        nearest = int(round(center))
        maximum_offset = int(math.floor(maximum_deviation)) + 2
        yielded: set[int] = set()
        for delta in range(maximum_offset + 1):
            candidates = (nearest,) if delta == 0 else (nearest + delta, nearest - delta)
            for value in candidates:
                if value in yielded:
                    continue
                yielded.add(value)
                if abs(value - center) <= maximum_deviation + 1e-12:
                    yield value

    def recurse(level: int, partial_norm: float) -> None:
        nonlocal nodes, node_limit_reached, slice_vector_limit_reached
        if node_limit_reached or slice_vector_limit_reached:
            return
        if level < 0:
            affine = tuple(
                affine_offset[j]
                + sum(coefficients[i] * rows[i][j] for i in range(dimension))
                for j in range(dimension)
            )
            vector = affine + (int(fixed_embedding_coordinate),)
            norm2 = sum(value * value for value in vector)
            if norm2 <= exact_acceptance_radius_squared:
                solutions.append(vector)
                exact_norms.append(norm2)
                if len(solutions) >= max_slice_vectors:
                    slice_vector_limit_reached = True
            return
        remaining = variable_radius_squared - partial_norm
        if remaining < -search_slack:
            return
        center = target_coordinates[level] - sum(
            coefficients[j] * mu[j][level] for j in range(level + 1, dimension)
        )
        deviation = math.sqrt(max(0.0, (remaining + search_slack) / norms[level]))
        for value in ordered_integers(center, deviation):
            if nodes >= node_limit:
                node_limit_reached = True
                return
            nodes += 1
            coefficients[level] = value
            component = value - center
            recurse(level - 1, partial_norm + component * component * norms[level])
            if node_limit_reached or slice_vector_limit_reached:
                return
        coefficients[level] = 0

    recurse(dimension - 1, 0.0)
    order = sorted(
        range(len(solutions)),
        key=lambda index: (exact_norms[index], solutions[index]),
    )
    complete = not node_limit_reached and not slice_vector_limit_reached
    return [solutions[index] for index in order], {
        "enumeration_nodes": nodes,
        "enumeration_node_limit": int(node_limit),
        "enumeration_node_limit_reached": node_limit_reached,
        "enumeration_slice_vector_limit": int(max_slice_vectors),
        "enumeration_slice_vector_limit_reached": slice_vector_limit_reached,
        "enumeration_solution_budget_reached": slice_vector_limit_reached,
        "enumeration_complete_within_bounds": complete,
        "raw_slice_vector_count": len(solutions),
        "enumerated_exact_norms": [exact_norms[index] for index in order],
        "fixed_embedding_coordinate": int(fixed_embedding_coordinate),
        "enumeration_label": "PROJECT_DERIVATION / constrained affine-slice CVP traversal",
    }


def build_extended_basis(
    *,
    A: Sequence[Sequence[int]],
    b: Sequence[int],
    H: Sequence[Sequence[int]],
    ell: Sequence[int],
    q: int,
    moduli: Sequence[int] | None = None,
) -> tuple[tuple[int, ...], ...]:
    """Build MN Eq. (20) in row-basis form for our ``A: m x n`` convention."""

    matrix = [[int(value) for value in row] for row in A]
    targets = [int(value) for value in b]
    hints = [[int(value) for value in row] for row in H]
    hint_targets = [int(value) for value in ell]
    m = len(matrix)
    n = len(matrix[0]) if matrix else (len(hints[0]) if hints else 0)
    r = len(hints)
    if len(targets) != m or len(hint_targets) != r:
        raise ValueError("incompatible A/b or H/ell dimensions")
    if any(len(row) != n for row in hints):
        raise ValueError("hint rows must have n columns")
    modulus_list = [q] * r if moduli is None else [int(value) for value in moduli]
    if len(modulus_list) != r:
        raise ValueError("one modulus is required per hint")
    dimension = m + r + n + 1
    basis = [[0] * dimension for _ in range(dimension)]
    for i in range(m):
        basis[i][i] = q
    for i, modulus in enumerate(modulus_list):
        basis[m + i][m + i] = modulus
    for secret_index in range(n):
        row = m + r + secret_index
        for sample in range(m):
            basis[row][sample] = matrix[sample][secret_index]
        for hint in range(r):
            basis[row][m + hint] = hints[hint][secret_index]
        basis[row][m + r + secret_index] = 1
    last = dimension - 1
    for sample in range(m):
        basis[last][sample] = targets[sample]
    for hint in range(r):
        basis[last][m + hint] = hint_targets[hint]
    basis[last][last] = 1
    return tuple(tuple(row) for row in basis)


def target_coefficients_and_vector(instance: Any) -> tuple[tuple[int, ...], tuple[int, ...]]:
    """Construct integer row coefficients proving ``(-e,0,s,-1)`` membership."""

    A, b, H, ell, q = instance.A, instance.b, instance.H, instance.ell, instance.q
    m, r, n = instance.m, len(H), instance.n
    raw_error = [sum(int(A[i][j]) * int(instance.s[j]) for j in range(n)) - int(b[i]) for i in range(m)]
    desired_error = [-int(value) for value in instance.e]
    top = []
    for desired, raw in zip(desired_error, raw_error):
        difference = desired - raw
        if difference % q:
            raise ValueError("LWE target membership congruence failed")
        top.append(difference // q)
    raw_hints = [sum(int(H[i][j]) * int(instance.s[j]) for j in range(n)) - int(ell[i]) for i in range(r)]
    hint_coefficients = []
    for raw in raw_hints:
        if raw % q:
            raise ValueError("hint target membership congruence failed")
        hint_coefficients.append(-raw // q)
    coefficients = tuple(top + hint_coefficients + list(instance.s) + [-1])
    target = tuple(desired_error + [0] * r + list(instance.s) + [-1])
    return coefficients, target


def multiply_row_combination(coefficients: Sequence[int], basis: Sequence[Sequence[int]]) -> tuple[int, ...]:
    """Multiply an integer row coefficient vector by a row basis."""

    if len(coefficients) != len(basis):
        raise ValueError("coefficient length differs from basis row count")
    return tuple(sum(int(coefficients[i]) * int(basis[i][j]) for i in range(len(basis))) for j in range(len(basis[0])))


def construct_modular_sublattice(
    *,
    A: Sequence[Sequence[int]],
    b: Sequence[int],
    H: Sequence[Sequence[int]],
    ell: Sequence[int],
    q: int,
    scaling_c: float,
) -> tuple[list[list[int]], dict[str, Any]]:
    """Adapt MN Algorithm 1 and return the compressed zero-hint-column basis."""

    construction_started = time.monotonic()
    try:
        from fpylll import IntegerMatrix, LLL
    except ImportError as exc:
        raise BackendUnavailable("fpylll is required for MN Construct-Sublattice") from exc
    matrix = [[int(value) for value in row] for row in A]
    hints = [[int(value) for value in row] for row in H]
    m = len(matrix)
    n = len(matrix[0])
    r = len(hints)
    lower_dimension = r + n + 1
    # [M; V; ell] for M=qI and H=(V,ell) in the paper's column convention.
    kernel = [[0] * r for _ in range(lower_dimension)]
    for i in range(r):
        kernel[i][i] = q
    for secret_index in range(n):
        for hint in range(r):
            kernel[r + secret_index][hint] = hints[hint][secret_index]
    for hint in range(r):
        kernel[-1][hint] = int(ell[hint])
    scale = int(math.ceil((2.0 ** (n / 2.0)) * scaling_c))
    lll_input = [[scale * value for value in row] + [int(i == j) for j in range(lower_dimension)] for i, row in enumerate(kernel)]
    reduced = IntegerMatrix.from_matrix(lll_input)
    transform = IntegerMatrix.identity(lower_dimension)
    started = time.monotonic()
    LLL.reduction(reduced, U=transform)
    reduction_time = time.monotonic() - started
    reduced_rows = [[int(reduced[i, j]) for j in range(reduced.ncols)] for i in range(reduced.nrows)]
    zero_rows = lower_dimension - r
    if any(reduced_rows[i][j] != 0 for i in range(zero_rows) for j in range(r)):
        raise SublatticeConstructionFailed("Algorithm 1 zero-block check failed; increase only within preregistered c grid")
    public_lower = [[0] * m for _ in range(lower_dimension)]
    for secret_index in range(n):
        for sample in range(m):
            public_lower[r + secret_index][sample] = matrix[sample][secret_index]
    public_lower[-1] = [int(value) for value in b]
    transformed_public = [
        [sum(int(transform[i, k]) * public_lower[k][j] for k in range(lower_dimension)) for j in range(m)]
        for i in range(lower_dimension)
    ]
    rectangular: list[list[int]] = []
    for i in range(m):
        rectangular.append([q * int(i == j) for j in range(m)] + [0] * (r + lower_dimension))
    for i in range(zero_rows):
        rectangular.append(transformed_public[i] + reduced_rows[i])
    # The retained rows are zero in the r scaled hint columns. Remove those
    # coordinates to obtain a square basis of dimension m+n+1.
    compressed = [row[:m] + row[m + r :] for row in rectangular]
    if len(compressed) != len(compressed[0]):
        raise AssertionError("compressed MN basis must be square")
    construction_elapsed = time.monotonic() - construction_started
    return compressed, {
        "source": "MN Section 5 Eq. (20), Algorithm 1 adaptation",
        "source_label": "LITERATURE_EXACT basis / LITERATURE_HEURISTIC scaling",
        "scale": scale,
        "scaling_c": scaling_c,
        "lll_transform_verified": True,
        "zero_block_verified": True,
        "reduction_time": reduction_time,
        "basis_time": max(0.0, construction_elapsed - reduction_time),
    }


def construct_constrained_slice_lattice(
    instance: Any,
    elimination: Any,
) -> tuple[list[list[int]], list[int], dict[str, Any]]:
    """Parameterize exactly the normalized ``t=-1`` MN embedding slice.

    The returned square row basis generates changes preserving every modular
    hint, while ``offset`` is one public hint-consistent affine point.  The
    ambient coordinates are ``(A*s-b+q*k, s)``; callers append the fixed
    embedding coordinate ``-1``.  This is an exact project derivation of the
    relevant slice, not a prior-aware pruning rule.
    """

    if tuple(elimination.remaining_rows):
        raise ValueError(
            "constrained MN slice currently requires full hint elimination (r_elim=r)"
        )
    if len(elimination.eliminated_rows) != len(instance.H):
        raise ValueError("constrained MN slice must account for every hint row")
    m, n, q = int(instance.m), int(instance.n), int(instance.q)
    pivot_indices = tuple(int(value) for value in elimination.pivot_indices)
    residual_indices = tuple(int(value) for value in elimination.residual_indices)
    if len(pivot_indices) + len(residual_indices) != n:
        raise ValueError("pivot and residual coordinates do not partition the secret")
    particular_secret = [0] * n
    for pivot_position, coordinate in enumerate(pivot_indices):
        particular_secret[coordinate] = centered_lift(elimination.c[pivot_position], q)
    offset_error = [
        sum(int(instance.A[row][column]) * particular_secret[column] for column in range(n))
        - int(instance.b[row])
        for row in range(m)
    ]
    offset = offset_error + particular_secret
    basis: list[list[int]] = []

    # Independent q-lifts of every error coordinate.
    for row in range(m):
        vector = [0] * (m + n)
        vector[row] = q
        basis.append(vector)

    # Independent q-lifts of pivot secret coordinates. Their induced A*s
    # change is included explicitly in the error block.
    for coordinate in pivot_indices:
        secret_delta = [0] * n
        secret_delta[coordinate] = q
        error_delta = [q * int(instance.A[row][coordinate]) for row in range(m)]
        basis.append(error_delta + secret_delta)

    # One generator per residual integer coordinate, with the affine pivot
    # change represented by a centered lift of -C[:,j].
    for residual_position, residual_coordinate in enumerate(residual_indices):
        secret_delta = [0] * n
        secret_delta[residual_coordinate] = 1
        for pivot_position, pivot_coordinate in enumerate(pivot_indices):
            secret_delta[pivot_coordinate] = centered_lift(
                -int(elimination.C[pivot_position][residual_position]),
                q,
            )
        error_delta = [
            sum(int(instance.A[row][column]) * secret_delta[column] for column in range(n))
            for row in range(m)
        ]
        basis.append(error_delta + secret_delta)

    if len(basis) != m + n or any(len(row) != m + n for row in basis):
        raise AssertionError("constrained MN slice basis must be square")
    for row in basis[m:]:
        secret_delta = row[m:]
        if any(
            sum(int(hint[column]) * secret_delta[column] for column in range(n)) % q
            for hint in instance.H
        ):
            raise AssertionError("constrained slice generator violates a modular hint")
    if any(
        (
            sum(int(hint[column]) * particular_secret[column] for column in range(n))
            - int(target)
        )
        % q
        for hint, target in zip(instance.H, instance.ell)
    ):
        raise AssertionError("constrained slice offset violates a modular hint")
    return basis, offset, {
        "source": "MN Section 5 embedding restricted to the normalized t=-1 slice",
        "source_label": "LITERATURE_EXACT embedding / PROJECT_DERIVATION constrained slice",
        "fixed_embedding_coordinate": -1,
        "slice_dimension": m + n,
        "ambient_embedding_dimension": m + n + 1,
        "full_hint_elimination_required": True,
        "truth_norm_used_for_radius": False,
    }


def canonical_b2_score_squared(
    instance: Any,
    elimination: Any,
    residual: Sequence[int],
) -> tuple[int, tuple[int, ...], tuple[int, ...]]:
    """Return the canonical full-secret/error B2 score for one residual."""

    full_mod = elimination.reconstruct(tuple(int(value) % instance.q for value in residual))
    full_secret = tuple(centered_vector(full_mod, instance.q))
    error = tuple(
        centered_vector(
            (
                sum(int(instance.A[row][column]) * full_secret[column] for column in range(instance.n))
                - int(instance.b[row])
                for row in range(instance.m)
            ),
            instance.q,
        )
    )
    score_squared = 1 + sum(value * value for value in full_secret) + sum(
        value * value for value in error
    )
    return score_squared, full_secret, error


def _canonicalize_constrained_slice_vectors(
    vectors: Sequence[Sequence[int]],
    *,
    instance: Any,
    elimination: Any,
) -> tuple[list[tuple[int, ...]], list[float], dict[str, int]]:
    """Map fixed-sign slice vectors to deterministically ordered candidates."""

    best: dict[tuple[int, ...], int] = {}
    duplicate_residuals = 0
    representative_score_violations = 0
    for row in vectors:
        if len(row) != instance.m + instance.n + 1 or int(row[-1]) != -1:
            raise ValueError("constrained slice emitted a vector outside t=-1")
        full_mod = tuple(int(value) % instance.q for value in row[instance.m : -1])
        residual = tuple(full_mod[index] for index in elimination.residual_indices)
        score_squared, _, _ = canonical_b2_score_squared(instance, elimination, residual)
        representative_norm_squared = sum(int(value) * int(value) for value in row)
        if score_squared > representative_norm_squared:
            representative_score_violations += 1
        if residual in best:
            duplicate_residuals += 1
            best[residual] = min(best[residual], score_squared)
        else:
            best[residual] = score_squared
    if representative_score_violations:
        raise AssertionError("canonical B2 score exceeds an enumerated representative norm")
    ordered = sorted(best, key=lambda residual: (best[residual], residual))
    return ordered, [-float(best[residual]) for residual in ordered], {
        "raw_slice_vector_count": len(vectors),
        "embedding_slice_vector_count": len(vectors),
        "duplicate_residual_count": duplicate_residuals,
        "canonical_unique_candidate_count": len(ordered),
        "canonical_score_violation_count": representative_score_violations,
    }


def _reduce_constrained_slice_basis(
    basis: Sequence[Sequence[int]],
    *,
    beta: int,
    beta_max: int,
    reduction_seed: int,
) -> tuple[list[list[int]], dict[str, Any]]:
    """Reduce a homogeneous constrained-slice basis without changing its set."""

    try:
        from fpylll import BKZ, FPLLL, IntegerMatrix, LLL
    except ImportError as exc:
        raise BackendUnavailable("fpylll is required for constrained-slice reduction") from exc
    if beta < 0 or beta > beta_max or beta_max > 30:
        raise ValueError("constrained-slice BKZ beta exceeds bounded protocol")
    integer_basis = IntegerMatrix.from_matrix([[int(value) for value in row] for row in basis])
    normalized_seed = int(reduction_seed) % (2**31 - 1)
    FPLLL.set_random_seed(normalized_seed)
    started = time.monotonic()
    LLL.reduction(integer_basis)
    if beta:
        BKZ.reduction(integer_basis, BKZ.Param(block_size=beta, max_loops=1))
    elapsed = time.monotonic() - started
    rows = [
        [int(integer_basis[i, j]) for j in range(integer_basis.ncols)]
        for i in range(integer_basis.nrows)
    ]
    return rows, {
        "candidate_reduction_time": elapsed,
        "reduction_seed": normalized_seed,
        "beta": int(beta),
        "reduction_role": "efficiency only; complete slice candidate set is basis invariant",
    }


def constrained_candidates_within_radius(
    instance: Any,
    elimination: Any,
    *,
    radius_squared: float,
    beta: int,
    beta_max: int,
    reduction_seed: int,
    node_limit: int,
    max_slice_vectors: int,
) -> CandidateList:
    """Return a complete canonical candidate ball or an explicitly censored list."""

    started = time.monotonic()
    basis, offset, metadata = construct_constrained_slice_lattice(instance, elimination)
    metadata["basis_time"] = time.monotonic() - started
    reduced_basis, reduction_metadata = _reduce_constrained_slice_basis(
        basis,
        beta=beta,
        beta_max=beta_max,
        reduction_seed=reduction_seed,
    )
    metadata.update(reduction_metadata)
    enumeration_started = time.monotonic()
    vectors, enumeration_metadata = bounded_cvp_schnorr_euchner(
        reduced_basis,
        offset=offset,
        radius_squared=float(radius_squared),
        max_slice_vectors=int(max_slice_vectors),
        node_limit=int(node_limit),
        fixed_embedding_coordinate=-1,
    )
    metadata.update(enumeration_metadata)
    metadata["enumeration_time"] = time.monotonic() - enumeration_started
    candidates, scores, extraction_metadata = _canonicalize_constrained_slice_vectors(
        vectors,
        instance=instance,
        elimination=elimination,
    )
    metadata.update(extraction_metadata)
    metadata.update(
        {
            "baseline": "B2_MN_CONSTRAINED_SLICE",
            "candidate_protocol": "COMPLETE_CONSTRAINED_RADIUS_BALL",
            "enumeration_radius_squared": float(radius_squared),
            "candidate_count": len(candidates),
            "candidate_extraction": "fixed t=-1 slice; canonical residual and B2-score deduplication",
            "embedding_slice_internal_constraint": True,
            "prior_internal_pruning": False,
            "predicate_integration": "leaf_postfilter",
        }
    )
    truth = tuple(instance.s[index] % instance.q for index in elimination.residual_indices)
    true_index = next((index for index, value in enumerate(candidates) if value == truth), None)
    return CandidateList(
        tuple(candidates),
        tuple(scores),
        true_index,
        "MNConstrainedSliceCandidateSource",
        metadata,
    )


def _extract_unique_residual_candidates(
    vectors: Sequence[Sequence[int]],
    *,
    m: int,
    n: int,
    q: int,
    residual_indices: Sequence[int],
) -> tuple[list[tuple[int, ...]], list[float], dict[str, int]]:
    """Canonicalize embedding signs and deduplicate residual-secret candidates.

    Bounded lattice enumeration normally emits both ``v`` and ``-v``.  Once
    the embedding coordinate is normalized to ``-1``, those two vectors map
    to the same secret candidate and must count only once in list-level
    selectivity statistics.
    """

    candidates: list[tuple[int, ...]] = []
    scores: list[float] = []
    candidate_indices: dict[tuple[int, ...], int] = {}
    eligible_embedding_vectors = 0
    duplicate_residuals = 0
    for row in vectors:
        last = int(row[-1])
        if abs(last) != 1:
            continue
        eligible_embedding_vectors += 1
        sign = -last
        full = tuple((sign * int(value)) % q for value in row[m : m + n])
        residual = tuple(full[j] for j in residual_indices)
        score = -float(sum(int(value) * int(value) for value in row))
        existing_index = candidate_indices.get(residual)
        if existing_index is not None:
            duplicate_residuals += 1
            # Retain the best (shortest-vector) score if distinct lattice
            # vectors project to the same residual secret.
            if score > scores[existing_index]:
                scores[existing_index] = score
            continue
        candidate_indices[residual] = len(candidates)
        candidates.append(residual)
        scores.append(score)
    return candidates, scores, {
        "eligible_embedding_vector_count": eligible_embedding_vectors,
        "duplicate_residual_count": duplicate_residuals,
        "unique_candidate_count": len(candidates),
    }


@dataclass
class MNGeneralCandidateSource:
    """Small-dimension B2 source based on the full-secret modular-hint lattice."""

    instance: Any = None
    elimination: Any = None
    config: dict[str, Any] | None = None

    def prepare(self, instance: Any, baseline_config: dict[str, Any]) -> None:
        self.instance = instance
        self.elimination = baseline_config["elimination"]
        self.config = dict(baseline_config)

    def generate(self, budget: int, rng: np.random.Generator) -> CandidateList:
        del rng
        if self.instance is None or self.config is None:
            raise RuntimeError("prepare must be called first")
        if self.instance.n > int(self.config.get("max_n", 80)):
            raise ValueError("MN candidate source is bounded to toy dimensions")
        basis, metadata = construct_modular_sublattice(
            A=self.instance.A,
            b=self.instance.b,
            H=self.instance.H,
            ell=self.instance.ell,
            q=self.instance.q,
            scaling_c=float(self.config.get("scaling_c", 1.0)),
        )
        try:
            from fpylll import BKZ, FPLLL, GSO, IntegerMatrix, LLL
        except ImportError as exc:
            raise BackendUnavailable("fpylll is required for B2 candidate generation") from exc
        integer_basis = IntegerMatrix.from_matrix(basis)
        reduction_seed = int(self.config.get("reduction_seed", 0)) % (2**31 - 1)
        FPLLL.set_random_seed(reduction_seed)
        metadata["reduction_seed"] = reduction_seed
        started = time.monotonic()
        LLL.reduction(integer_basis)
        beta = int(self.config.get("beta", 0))
        if beta:
            beta_max = int(self.config.get("beta_max", 30))
            if beta > beta_max or beta_max > 30:
                raise ValueError("BKZ beta exceeds bounded protocol")
            BKZ.reduction(integer_basis, BKZ.Param(block_size=beta, max_loops=1))
        metadata["candidate_reduction_time"] = time.monotonic() - started
        gso = GSO.Mat(integer_basis)
        if not gso.update_gso():
            raise RuntimeError("GSO update failed after reduction")
        radius_multiplier = float(self.config.get("radius_multiplier", 1.05))
        radius_squared = radius_multiplier * radius_multiplier * float(gso.get_r(0, 0))
        enumeration_started = time.monotonic()
        reduced_basis_rows = [
            [int(integer_basis[i, j]) for j in range(integer_basis.ncols)]
            for i in range(integer_basis.nrows)
        ]
        vectors, enumeration_metadata = bounded_schnorr_euchner(
            reduced_basis_rows,
            radius_squared=radius_squared,
            max_solutions=budget,
            node_limit=int(self.config.get("enumeration_node_limit", 100_000)),
        )
        metadata.update(enumeration_metadata)
        metadata["enumeration_time"] = time.monotonic() - enumeration_started
        metadata["enumeration_radius_squared"] = radius_squared
        metadata["radius_multiplier"] = radius_multiplier
        m, n = self.instance.m, self.instance.n
        candidates, scores, extraction_metadata = _extract_unique_residual_candidates(
            vectors,
            m=m,
            n=n,
            q=self.instance.q,
            residual_indices=self.elimination.residual_indices,
        )
        truth = tuple(self.instance.s[j] % self.instance.q for j in self.elimination.residual_indices)
        true_index = next((i for i, candidate in enumerate(candidates) if candidate == truth), None)
        metadata.update(
            {
                "baseline": "B2_MN_GENERAL",
                "candidate_count": len(candidates),
                **extraction_metadata,
                "candidate_extraction": "bounded enumerated vectors with embedding coordinate +/-1",
                "enumeration_internal_pruning": False,
                "predicate_integration": "leaf_postfilter",
            }
        )
        return CandidateList(tuple(candidates), tuple(scores), true_index, "MNGeneralCandidateSource", metadata)


@dataclass
class MNConstrainedTopKCandidateSource:
    """Certified B2 top-K source on the normalized MN embedding slice.

    Radius thresholds are public, finite, and configuration supplied.  The
    first *complete* constrained ball containing at least ``K`` canonical
    residual candidates certifies the deterministic ordering by
    ``(canonical B2 score, residual lexicographic order)``.  A resource-limit
    prefix is never returned as top-K evidence.
    """

    instance: Any = None
    elimination: Any = None
    config: dict[str, Any] | None = None

    def prepare(self, instance: Any, baseline_config: dict[str, Any]) -> None:
        self.instance = instance
        self.elimination = baseline_config["elimination"]
        self.config = dict(baseline_config)

    def generate(self, budget: int, rng: np.random.Generator) -> CandidateList:
        del rng
        if self.instance is None or self.elimination is None or self.config is None:
            raise RuntimeError("prepare must be called first")
        if self.instance.n > int(self.config.get("max_n", 80)):
            raise ValueError("constrained MN source is bounded to toy dimensions")
        top_k = int(budget)
        if top_k <= 0:
            raise ValueError("certified top-K must be positive")
        nested_top_k = sorted({int(value) for value in self.config.get("top_k_values", [top_k])})
        if not nested_top_k or nested_top_k[-1] != top_k or nested_top_k[0] <= 0:
            raise ValueError("top_k_values must be positive and end at the requested K")
        thresholds = sorted(
            {float(value) for value in self.config.get("score_radius_squared_grid", [])}
        )
        if not thresholds or thresholds[0] <= 1.0:
            raise ValueError("a finite public score_radius_squared_grid above one is required")
        maximum_steps = int(self.config.get("max_radius_steps", len(thresholds)))
        if len(thresholds) > maximum_steps:
            raise ValueError("score-radius grid exceeds the frozen step cap")

        basis_started = time.monotonic()
        basis, offset, metadata = construct_constrained_slice_lattice(
            self.instance,
            self.elimination,
        )
        metadata["basis_time"] = time.monotonic() - basis_started
        reduced_basis, reduction_metadata = _reduce_constrained_slice_basis(
            basis,
            beta=int(self.config.get("beta", 0)),
            beta_max=int(self.config.get("beta_max", 30)),
            reduction_seed=int(self.config.get("reduction_seed", 0)),
        )
        metadata.update(reduction_metadata)
        attempts: list[dict[str, Any]] = []
        total_nodes = 0
        total_raw_vectors = 0
        total_enumeration_time = 0.0
        for threshold in thresholds:
            enumeration_started = time.monotonic()
            vectors, enumeration_metadata = bounded_cvp_schnorr_euchner(
                reduced_basis,
                offset=offset,
                radius_squared=threshold,
                max_slice_vectors=int(self.config.get("max_slice_vectors_per_radius", 100_000)),
                node_limit=int(self.config.get("enumeration_node_limit", 1_000_000)),
                fixed_embedding_coordinate=-1,
            )
            elapsed = time.monotonic() - enumeration_started
            candidates, scores, extraction_metadata = _canonicalize_constrained_slice_vectors(
                vectors,
                instance=self.instance,
                elimination=self.elimination,
            )
            total_nodes += int(enumeration_metadata["enumeration_nodes"])
            total_raw_vectors += int(enumeration_metadata["raw_slice_vector_count"])
            total_enumeration_time += elapsed
            attempt = {
                "score_radius_squared": threshold,
                "enumeration_time": elapsed,
                **enumeration_metadata,
                **extraction_metadata,
            }
            attempts.append(attempt)
            if not bool(enumeration_metadata["enumeration_complete_within_bounds"]):
                raise CertifiedTopKUnavailable(
                    "RESOURCE_LIMIT: constrained candidate ball is censored before top-K certification",
                    {
                        **metadata,
                        "candidate_protocol": "CERTIFIED_CONSTRAINED_TOP_K",
                        "top_k_requested": top_k,
                        "top_k_certified": False,
                        "radius_attempts": attempts,
                        "enumeration_nodes_total_across_attempts": total_nodes,
                        "raw_slice_vectors_total_across_attempts": total_raw_vectors,
                    },
                )
            if len(candidates) < top_k:
                continue
            selected_candidates = candidates[:top_k]
            selected_scores = scores[:top_k]
            truth = tuple(
                self.instance.s[index] % self.instance.q
                for index in self.elimination.residual_indices
            )
            true_index = next(
                (index for index, candidate in enumerate(selected_candidates) if candidate == truth),
                None,
            )
            metadata.update(
                {
                    "baseline": "B2_MN_CONSTRAINED_TOP_K",
                    "candidate_protocol": "CERTIFIED_CONSTRAINED_TOP_K",
                    "candidate_order": "canonical B2 score ascending, then residual lexicographic",
                    "top_k_requested": top_k,
                    "nested_top_k": nested_top_k,
                    "top_k_certified": True,
                    "certification_radius_squared": threshold,
                    "kth_candidate_score_squared": -float(selected_scores[-1]),
                    "canonical_unique_candidates_in_certification_ball": len(candidates),
                    "candidate_count": len(selected_candidates),
                    "radius_attempts": attempts,
                    "radius_selection_uses_true_norm": False,
                    "radius_selection_uses_prior_pass_rate": False,
                    "enumeration_nodes": int(enumeration_metadata["enumeration_nodes"]),
                    "enumeration_nodes_total_across_attempts": total_nodes,
                    "raw_slice_vector_count": int(
                        enumeration_metadata["raw_slice_vector_count"]
                    ),
                    "raw_slice_vectors_total_across_attempts": total_raw_vectors,
                    "embedding_slice_vector_count": int(
                        extraction_metadata["embedding_slice_vector_count"]
                    ),
                    "duplicate_residual_count": int(
                        extraction_metadata["duplicate_residual_count"]
                    ),
                    "canonical_unique_candidate_count": int(
                        extraction_metadata["canonical_unique_candidate_count"]
                    ),
                    "enumeration_time": total_enumeration_time,
                    "enumeration_complete_within_bounds": True,
                    "enumeration_node_limit_reached": False,
                    "enumeration_solution_budget_reached": False,
                    "candidate_extraction": "fixed t=-1 slice; canonical residual and B2-score deduplication",
                    "embedding_slice_internal_constraint": True,
                    "prior_internal_pruning": False,
                    "predicate_integration": "leaf_postfilter",
                }
            )
            return CandidateList(
                tuple(selected_candidates),
                tuple(selected_scores),
                true_index,
                "MNConstrainedTopKCandidateSource",
                metadata,
            )
        raise CertifiedTopKUnavailable(
            "RESOURCE_LIMIT: public radius grid ended before K unique candidates were certified",
            {
                **metadata,
                "candidate_protocol": "CERTIFIED_CONSTRAINED_TOP_K",
                "top_k_requested": top_k,
                "top_k_certified": False,
                "radius_attempts": attempts,
                "enumeration_nodes_total_across_attempts": total_nodes,
                "raw_slice_vectors_total_across_attempts": total_raw_vectors,
                "enumeration_time": total_enumeration_time,
            },
        )
