"""May--Nowakowski Section 5 full-secret modular-hint construction.

Equation (20) is implemented exactly. The optional sublattice/reduction path
adapts Algorithm 1 to the modular-hint block and requires ``fpylll``. Its
scaling choice remains a documented heuristic and therefore cannot silently
serve as a headline B2 result without the recorded invariant checks.
"""

from __future__ import annotations

import math
import time
from dataclasses import dataclass
from typing import Any, Sequence

import numpy as np

from .base import CandidateList


class BackendUnavailable(RuntimeError):
    """Raised when the optional faithful-small lattice dependency is absent."""


class SublatticeConstructionFailed(RuntimeError):
    """Raised when Algorithm 1's zero-block check fails."""


def bounded_schnorr_euchner(
    basis: Sequence[Sequence[int]],
    *,
    radius_squared: float,
    max_solutions: int,
    node_limit: int,
) -> tuple[list[tuple[int, ...]], dict[str, Any]]:
    """Enumerate short lattice vectors with an in-loop hard node limit.

    The lattice is generated by the rows of ``basis``. GSO data comes from
    fpylll, while traversal and its node counter are implemented here so the
    configured node limit is enforced before visiting another node. Returned
    vectors are checked again with exact integer norms.
    """

    try:
        from fpylll import GSO, IntegerMatrix
    except ImportError as exc:
        raise BackendUnavailable("fpylll is required for bounded GSO enumeration") from exc
    if radius_squared <= 0 or max_solutions <= 0 or node_limit <= 0:
        raise ValueError("radius, solution budget, and node limit must be positive")
    rows = [[int(value) for value in row] for row in basis]
    integer_basis = IntegerMatrix.from_matrix(rows)
    gso = GSO.Mat(integer_basis)
    if not gso.update_gso():
        raise RuntimeError("GSO update failed")
    dimension = integer_basis.nrows
    norms = [float(gso.get_r(i, i)) for i in range(dimension)]
    if any(not math.isfinite(value) or value <= 0 for value in norms):
        raise RuntimeError("invalid GSO diagonal")
    mu = [[0.0] * dimension for _ in range(dimension)]
    for i in range(dimension):
        for j in range(i):
            mu[i][j] = float(gso.get_mu(i, j))
    coefficients = [0] * dimension
    solutions: list[tuple[int, ...]] = []
    exact_norms: list[int] = []
    nodes = 0
    node_limit_reached = False
    solution_budget_reached = False

    def ordered_integers(center: float, maximum_deviation: float):
        nearest = int(round(center))
        maximum_offset = int(math.floor(maximum_deviation)) + 2
        yielded: set[int] = set()
        for offset in range(maximum_offset + 1):
            candidates = (nearest,) if offset == 0 else (nearest + offset, nearest - offset)
            for value in candidates:
                if value in yielded:
                    continue
                yielded.add(value)
                if abs(value - center) <= maximum_deviation + 1e-12:
                    yield value

    def recurse(level: int, partial_norm: float) -> None:
        nonlocal nodes, node_limit_reached, solution_budget_reached
        if node_limit_reached or solution_budget_reached:
            return
        if level < 0:
            if all(value == 0 for value in coefficients):
                return
            vector = tuple(
                sum(coefficients[i] * rows[i][j] for i in range(dimension))
                for j in range(len(rows[0]))
            )
            norm2 = sum(value * value for value in vector)
            if norm2 <= radius_squared * (1.0 + 1e-12):
                solutions.append(vector)
                exact_norms.append(norm2)
                if len(solutions) >= max_solutions:
                    solution_budget_reached = True
            return
        remaining = radius_squared - partial_norm
        if remaining < 0:
            return
        center = -sum(coefficients[j] * mu[j][level] for j in range(level + 1, dimension))
        deviation = math.sqrt(max(0.0, remaining / norms[level]))
        for value in ordered_integers(center, deviation):
            if nodes >= node_limit:
                node_limit_reached = True
                return
            nodes += 1
            coefficients[level] = value
            component = value - center
            recurse(level - 1, partial_norm + component * component * norms[level])
            if node_limit_reached or solution_budget_reached:
                return
        coefficients[level] = 0

    recurse(dimension - 1, 0.0)
    order = sorted(range(len(solutions)), key=lambda index: exact_norms[index])
    return [solutions[index] for index in order], {
        "enumeration_nodes": nodes,
        "enumeration_node_limit": node_limit,
        "enumeration_node_limit_reached": node_limit_reached,
        "enumeration_solution_budget_reached": solution_budget_reached,
        "enumeration_complete_within_bounds": not node_limit_reached and not solution_budget_reached,
        "enumerated_exact_norms": [exact_norms[index] for index in order],
        "enumeration_label": "PROJECT_DERIVATION / bounded Schnorr-Euchner traversal",
    }


def build_extended_basis(
    *,
    A: Sequence[Sequence[int]],
    b: Sequence[int],
    H: Sequence[Sequence[int]],
    ell: Sequence[int],
    q: int,
    moduli: Sequence[int] | None = None,
) -> tuple[tuple[int, ...], ...]:
    """Build MN Eq. (20) in row-basis form for our ``A: m x n`` convention."""

    matrix = [[int(value) for value in row] for row in A]
    targets = [int(value) for value in b]
    hints = [[int(value) for value in row] for row in H]
    hint_targets = [int(value) for value in ell]
    m = len(matrix)
    n = len(matrix[0]) if matrix else (len(hints[0]) if hints else 0)
    r = len(hints)
    if len(targets) != m or len(hint_targets) != r:
        raise ValueError("incompatible A/b or H/ell dimensions")
    if any(len(row) != n for row in hints):
        raise ValueError("hint rows must have n columns")
    modulus_list = [q] * r if moduli is None else [int(value) for value in moduli]
    if len(modulus_list) != r:
        raise ValueError("one modulus is required per hint")
    dimension = m + r + n + 1
    basis = [[0] * dimension for _ in range(dimension)]
    for i in range(m):
        basis[i][i] = q
    for i, modulus in enumerate(modulus_list):
        basis[m + i][m + i] = modulus
    for secret_index in range(n):
        row = m + r + secret_index
        for sample in range(m):
            basis[row][sample] = matrix[sample][secret_index]
        for hint in range(r):
            basis[row][m + hint] = hints[hint][secret_index]
        basis[row][m + r + secret_index] = 1
    last = dimension - 1
    for sample in range(m):
        basis[last][sample] = targets[sample]
    for hint in range(r):
        basis[last][m + hint] = hint_targets[hint]
    basis[last][last] = 1
    return tuple(tuple(row) for row in basis)


def target_coefficients_and_vector(instance: Any) -> tuple[tuple[int, ...], tuple[int, ...]]:
    """Construct integer row coefficients proving ``(-e,0,s,-1)`` membership."""

    A, b, H, ell, q = instance.A, instance.b, instance.H, instance.ell, instance.q
    m, r, n = instance.m, len(H), instance.n
    raw_error = [sum(int(A[i][j]) * int(instance.s[j]) for j in range(n)) - int(b[i]) for i in range(m)]
    desired_error = [-int(value) for value in instance.e]
    top = []
    for desired, raw in zip(desired_error, raw_error):
        difference = desired - raw
        if difference % q:
            raise ValueError("LWE target membership congruence failed")
        top.append(difference // q)
    raw_hints = [sum(int(H[i][j]) * int(instance.s[j]) for j in range(n)) - int(ell[i]) for i in range(r)]
    hint_coefficients = []
    for raw in raw_hints:
        if raw % q:
            raise ValueError("hint target membership congruence failed")
        hint_coefficients.append(-raw // q)
    coefficients = tuple(top + hint_coefficients + list(instance.s) + [-1])
    target = tuple(desired_error + [0] * r + list(instance.s) + [-1])
    return coefficients, target


def multiply_row_combination(coefficients: Sequence[int], basis: Sequence[Sequence[int]]) -> tuple[int, ...]:
    """Multiply an integer row coefficient vector by a row basis."""

    if len(coefficients) != len(basis):
        raise ValueError("coefficient length differs from basis row count")
    return tuple(sum(int(coefficients[i]) * int(basis[i][j]) for i in range(len(basis))) for j in range(len(basis[0])))


def construct_modular_sublattice(
    *,
    A: Sequence[Sequence[int]],
    b: Sequence[int],
    H: Sequence[Sequence[int]],
    ell: Sequence[int],
    q: int,
    scaling_c: float,
) -> tuple[list[list[int]], dict[str, Any]]:
    """Adapt MN Algorithm 1 and return the compressed zero-hint-column basis."""

    construction_started = time.monotonic()
    try:
        from fpylll import IntegerMatrix, LLL
    except ImportError as exc:
        raise BackendUnavailable("fpylll is required for MN Construct-Sublattice") from exc
    matrix = [[int(value) for value in row] for row in A]
    hints = [[int(value) for value in row] for row in H]
    m = len(matrix)
    n = len(matrix[0])
    r = len(hints)
    lower_dimension = r + n + 1
    # [M; V; ell] for M=qI and H=(V,ell) in the paper's column convention.
    kernel = [[0] * r for _ in range(lower_dimension)]
    for i in range(r):
        kernel[i][i] = q
    for secret_index in range(n):
        for hint in range(r):
            kernel[r + secret_index][hint] = hints[hint][secret_index]
    for hint in range(r):
        kernel[-1][hint] = int(ell[hint])
    scale = int(math.ceil((2.0 ** (n / 2.0)) * scaling_c))
    lll_input = [[scale * value for value in row] + [int(i == j) for j in range(lower_dimension)] for i, row in enumerate(kernel)]
    reduced = IntegerMatrix.from_matrix(lll_input)
    transform = IntegerMatrix.identity(lower_dimension)
    started = time.monotonic()
    LLL.reduction(reduced, U=transform)
    reduction_time = time.monotonic() - started
    reduced_rows = [[int(reduced[i, j]) for j in range(reduced.ncols)] for i in range(reduced.nrows)]
    zero_rows = lower_dimension - r
    if any(reduced_rows[i][j] != 0 for i in range(zero_rows) for j in range(r)):
        raise SublatticeConstructionFailed("Algorithm 1 zero-block check failed; increase only within preregistered c grid")
    public_lower = [[0] * m for _ in range(lower_dimension)]
    for secret_index in range(n):
        for sample in range(m):
            public_lower[r + secret_index][sample] = matrix[sample][secret_index]
    public_lower[-1] = [int(value) for value in b]
    transformed_public = [
        [sum(int(transform[i, k]) * public_lower[k][j] for k in range(lower_dimension)) for j in range(m)]
        for i in range(lower_dimension)
    ]
    rectangular: list[list[int]] = []
    for i in range(m):
        rectangular.append([q * int(i == j) for j in range(m)] + [0] * (r + lower_dimension))
    for i in range(zero_rows):
        rectangular.append(transformed_public[i] + reduced_rows[i])
    # The retained rows are zero in the r scaled hint columns. Remove those
    # coordinates to obtain a square basis of dimension m+n+1.
    compressed = [row[:m] + row[m + r :] for row in rectangular]
    if len(compressed) != len(compressed[0]):
        raise AssertionError("compressed MN basis must be square")
    construction_elapsed = time.monotonic() - construction_started
    return compressed, {
        "source": "MN Section 5 Eq. (20), Algorithm 1 adaptation",
        "source_label": "LITERATURE_EXACT basis / LITERATURE_HEURISTIC scaling",
        "scale": scale,
        "scaling_c": scaling_c,
        "lll_transform_verified": True,
        "zero_block_verified": True,
        "reduction_time": reduction_time,
        "basis_time": max(0.0, construction_elapsed - reduction_time),
    }


def _extract_unique_residual_candidates(
    vectors: Sequence[Sequence[int]],
    *,
    m: int,
    n: int,
    q: int,
    residual_indices: Sequence[int],
) -> tuple[list[tuple[int, ...]], list[float], dict[str, int]]:
    """Canonicalize embedding signs and deduplicate residual-secret candidates.

    Bounded lattice enumeration normally emits both ``v`` and ``-v``.  Once
    the embedding coordinate is normalized to ``-1``, those two vectors map
    to the same secret candidate and must count only once in list-level
    selectivity statistics.
    """

    candidates: list[tuple[int, ...]] = []
    scores: list[float] = []
    candidate_indices: dict[tuple[int, ...], int] = {}
    eligible_embedding_vectors = 0
    duplicate_residuals = 0
    for row in vectors:
        last = int(row[-1])
        if abs(last) != 1:
            continue
        eligible_embedding_vectors += 1
        sign = -last
        full = tuple((sign * int(value)) % q for value in row[m : m + n])
        residual = tuple(full[j] for j in residual_indices)
        score = -float(sum(int(value) * int(value) for value in row))
        existing_index = candidate_indices.get(residual)
        if existing_index is not None:
            duplicate_residuals += 1
            # Retain the best (shortest-vector) score if distinct lattice
            # vectors project to the same residual secret.
            if score > scores[existing_index]:
                scores[existing_index] = score
            continue
        candidate_indices[residual] = len(candidates)
        candidates.append(residual)
        scores.append(score)
    return candidates, scores, {
        "eligible_embedding_vector_count": eligible_embedding_vectors,
        "duplicate_residual_count": duplicate_residuals,
        "unique_candidate_count": len(candidates),
    }


@dataclass
class MNGeneralCandidateSource:
    """Small-dimension B2 source based on the full-secret modular-hint lattice."""

    instance: Any = None
    elimination: Any = None
    config: dict[str, Any] | None = None

    def prepare(self, instance: Any, baseline_config: dict[str, Any]) -> None:
        self.instance = instance
        self.elimination = baseline_config["elimination"]
        self.config = dict(baseline_config)

    def generate(self, budget: int, rng: np.random.Generator) -> CandidateList:
        del rng
        if self.instance is None or self.config is None:
            raise RuntimeError("prepare must be called first")
        if self.instance.n > int(self.config.get("max_n", 80)):
            raise ValueError("MN candidate source is bounded to toy dimensions")
        basis, metadata = construct_modular_sublattice(
            A=self.instance.A,
            b=self.instance.b,
            H=self.instance.H,
            ell=self.instance.ell,
            q=self.instance.q,
            scaling_c=float(self.config.get("scaling_c", 1.0)),
        )
        try:
            from fpylll import BKZ, FPLLL, GSO, IntegerMatrix, LLL
        except ImportError as exc:
            raise BackendUnavailable("fpylll is required for B2 candidate generation") from exc
        integer_basis = IntegerMatrix.from_matrix(basis)
        reduction_seed = int(self.config.get("reduction_seed", 0)) % (2**31 - 1)
        FPLLL.set_random_seed(reduction_seed)
        metadata["reduction_seed"] = reduction_seed
        started = time.monotonic()
        LLL.reduction(integer_basis)
        beta = int(self.config.get("beta", 0))
        if beta:
            beta_max = int(self.config.get("beta_max", 30))
            if beta > beta_max or beta_max > 30:
                raise ValueError("BKZ beta exceeds bounded protocol")
            BKZ.reduction(integer_basis, BKZ.Param(block_size=beta, max_loops=1))
        metadata["candidate_reduction_time"] = time.monotonic() - started
        gso = GSO.Mat(integer_basis)
        if not gso.update_gso():
            raise RuntimeError("GSO update failed after reduction")
        radius_multiplier = float(self.config.get("radius_multiplier", 1.05))
        radius_squared = radius_multiplier * radius_multiplier * float(gso.get_r(0, 0))
        enumeration_started = time.monotonic()
        reduced_basis_rows = [
            [int(integer_basis[i, j]) for j in range(integer_basis.ncols)]
            for i in range(integer_basis.nrows)
        ]
        vectors, enumeration_metadata = bounded_schnorr_euchner(
            reduced_basis_rows,
            radius_squared=radius_squared,
            max_solutions=budget,
            node_limit=int(self.config.get("enumeration_node_limit", 100_000)),
        )
        metadata.update(enumeration_metadata)
        metadata["enumeration_time"] = time.monotonic() - enumeration_started
        metadata["enumeration_radius_squared"] = radius_squared
        metadata["radius_multiplier"] = radius_multiplier
        m, n = self.instance.m, self.instance.n
        candidates, scores, extraction_metadata = _extract_unique_residual_candidates(
            vectors,
            m=m,
            n=n,
            q=self.instance.q,
            residual_indices=self.elimination.residual_indices,
        )
        truth = tuple(self.instance.s[j] % self.instance.q for j in self.elimination.residual_indices)
        true_index = next((i for i, candidate in enumerate(candidates) if candidate == truth), None)
        metadata.update(
            {
                "baseline": "B2_MN_GENERAL",
                "candidate_count": len(candidates),
                **extraction_metadata,
                "candidate_extraction": "bounded enumerated vectors with embedding coordinate +/-1",
                "enumeration_internal_pruning": False,
                "predicate_integration": "leaf_postfilter",
            }
        )
        return CandidateList(tuple(candidates), tuple(scores), true_index, "MNGeneralCandidateSource", metadata)
